### ISSUE TITLE
could i get admin rights here?

### ISSUE THREAD

**Issue by kidd** [dash-docs-el/dash-to-dash#1]
Hi there, I created this simple repo to substitute a flaky app I had been hosting in heroku to fetch the user contributed docsets.

The idea is to enable github pages for this repo and make travis update the list of packages daily.  The `dash-docs` clients will be able to fetch the data from here.

I'd need to be able to change the description of the package (I'd need to substitute kidd.github/... to dash-docs-el.github/... also checking travis and the gh-pages

**Comment by kidd** [comment]
well, looks like just changing the url in the description of the repo to the url that lives under `dash-docs-el` should be enough.

I can't update the travis build though.

**Comment by areina** [comment]
Hey @kidd, you should mention @gilbertw1, probably he isn't aware of this issue.

**Comment by kidd** [comment]
TIL. thx!

**Comment by gilbertw1** [comment]
Hey, yep I'm just seeing this. I've given you admin privileges. Let me know if you need anything else!

**Comment by kidd** [comment]
Thanks!
@gilbertw1 I sent you another authorization request to enable travis deploying the json automagically.

**Comment by gilbertw1** [comment]
I've approved it
